### ISSUE TITLE
Reunião de alinhamento

### ISSUE THREAD

**Issue by lizagmendes** [Equipe-Botcem/Equipe-Botcem.github.io#31]
Primeira reunião da equipe. Tem o objetivo de definir possíveis caminhos para se seguir com o robô, marcar reuniões semanais e separar cada membro para uma função específica. 
Marcada para terça-feira 24/10, 15h.

**Comment by arthurhn** [comment]
Liza, eu vi que essa issue ficou atrelada ao repositório da wiki, se tu puder criar um repositório do novo Omega, acho que "Seguidor Omega 23.2" fica legal, vai ficar mais fácil não só de vocês acharem, como vai ficar mais organizado também
